"use client";

import Image from "next/image";
import {useEffect,useRef,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";

export function ScratchReveal(){
  const scratch=useRef<HTMLCanvasElement>(null),fireworks=useRef<HTMLCanvasElement>(null);const [revealed,setRevealed]=useState(false);const drawing=useRef(false);
  useEffect(()=>{const c=scratch.current;if(!c)return;const ctx=c.getContext("2d")!;const paint=()=>{c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const g=ctx.createLinearGradient(0,0,c.clientWidth,c.clientHeight);g.addColorStop(0,"#3b0714");g.addColorStop(.5,"#b48b4c");g.addColorStop(1,"#24050d");ctx.fillStyle=g;ctx.fillRect(0,0,c.clientWidth,c.clientHeight);ctx.fillStyle="#f6e8cb";ctx.textAlign="center";ctx.font="italic 34px Cormorant Garamond";ctx.fillText("Scratch to reveal our forever",c.clientWidth/2,c.clientHeight/2);ctx.font="10px Montserrat";ctx.letterSpacing="4px";ctx.fillText("A LITTLE MAGIC AWAITS",c.clientWidth/2,c.clientHeight/2+35)};paint();addEventListener("resize",paint);return()=>removeEventListener("resize",paint)},[]);
  const scratchAt=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const c=scratch.current!,r=c.getBoundingClientRect(),ctx=c.getContext("2d")!;ctx.globalCompositeOperation="destination-out";ctx.beginPath();ctx.arc(e.clientX-r.left,e.clientY-r.top,42,0,Math.PI*2);ctx.fill();let cleared=0;const data=ctx.getImageData(0,0,c.width,c.height).data;for(let i=3;i<data.length;i+=80)if(data[i]===0)cleared++;if(cleared>data.length/80*.32){setRevealed(true);gsap.to(c,{opacity:0,duration:.9,pointerEvents:"none"})}};
  const burst=(e:React.PointerEvent)=>{if(!revealed)return;const c=fireworks.current!,ctx=c.getContext("2d")!,r=c.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const particles=Array.from({length:70},(_,i)=>{const a=Math.PI*2*i/70,s=2+Math.random()*6;return{x:e.clientX-r.left,y:e.clientY-r.top,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,color:["#ffd477","#fff4c7","#b52b4a","#ff8d3a"][i%4]}});let frame=0;const tick=()=>{ctx.clearRect(0,0,r.width,r.height);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.055;p.life-=.016;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,2.2,0,Math.PI*2);ctx.fill()});if(frame++<72)requestAnimationFrame(tick);else ctx.clearRect(0,0,r.width,r.height)};tick()};
  return <section className="scratch-section"><header><span>Not every love is seen at first glance</span><h2>Reveal a little <em>magic</em></h2></header><div className="scratch-frame" onPointerDown={burst}><Image src="/images/couple.png" alt="Ankit and Shreya" fill sizes="(max-width:800px) 92vw, 760px"/><canvas ref={fireworks} className="fireworks"/><canvas ref={scratch} className="scratch" onPointerDown={e=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);scratchAt(e)}} onPointerMove={scratchAt} onPointerUp={()=>drawing.current=false}/>{revealed&&<div className="tap-fireworks">Tap the photograph for fireworks ✦</div>}</div></section>
}

export function Journey(){
  const section=useRef<HTMLElement>(null),path=useRef<SVGPathElement>(null),car=useRef<HTMLDivElement>(null),route=useRef<SVGPathElement>(null);
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const p=path.current!,c=car.current!,r=route.current!,length=p.getTotalLength();r.style.strokeDasharray=`${length}`;r.style.strokeDashoffset=`${length}`;const st=ScrollTrigger.create({trigger:section.current,start:"top top",end:"bottom bottom",scrub:1,onUpdate:self=>{const progress=self.progress,point=p.getPointAtLength(length*progress),next=p.getPointAtLength(Math.min(length,length*progress+2));gsap.set(c,{x:point.x,y:point.y,rotation:Math.atan2(next.y-point.y,next.x-point.x)*180/Math.PI});r.style.strokeDashoffset=`${length*(1-progress)}`}});return()=>st.kill()},[]);
  return <section ref={section} className="journey"><div className="journey-sticky"><div className="journey-copy"><span>A journey of hearts</span><h2>From Gonda<br/><em>to forever.</em></h2><p>Scroll to carry our story across cities, memories and miles.</p></div><div className="map-card"><svg viewBox="0 0 900 520" role="img" aria-label="Journey from Gonda to Madhya Pradesh"><defs><filter id="glow"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path className="india-line" d="M120 94 C235 35 354 68 438 130 C530 198 660 150 780 238 C832 277 810 370 718 412 C599 466 467 432 369 472 C260 516 145 443 109 354 C79 278 155 222 120 94Z"/><path ref={path} className="route-guide" d="M235 130 C300 170 330 245 410 250 C510 258 545 350 675 385"/><path ref={route} className="route-live" d="M235 130 C300 170 330 245 410 250 C510 258 545 350 675 385"/><circle cx="235" cy="130" r="7"/><circle cx="675" cy="385" r="7"/><text x="190" y="105">GONDA</text><text x="635" y="430">MADHYA PRADESH</text></svg><div ref={car} className="wedding-car">❋<span>▰</span></div><div className="route-label from">Where it began</div><div className="route-label to">Where forever awaits</div></div><div className="miles">MILES APART <i/> HEARTS TOGETHER</div></div></section>
}
